"""chnage latitude and longitude from optional to nonnullable

Revision ID: 58c4b1d0db58
Revises: b56df78e8051
Create Date: 2026-01-15 11:08:33.697393

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "58c4b1d0db58"
down_revision = "b56df78e8051"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["id"])

    with op.batch_alter_table("site", schema=None) as batch_op:
        batch_op.alter_column(
            "latitude", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
        )
        batch_op.alter_column(
            "longitude", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("site", schema=None) as batch_op:
        batch_op.alter_column(
            "longitude", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
        )
        batch_op.alter_column(
            "latitude", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
        )

    with op.batch_alter_table("service", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
